### PR TITLE
Fix/149/fix media art tests

### LINKED ISSUE #149: Fix tests in MediatR/Media/Art
Image

### PR DESCRIPTION
**Pull request by Andriy1409**
dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Create/CreateArtHandlerTests.cs [hunk 1]
```diff
@@ -12,172 +12,172 @@
...
-            var result = await _handler.Handle(command, CancellationToken.None);
+        // Act
+        Func<Task> act = async () => await _handler.Handle(command, CancellationToken.None);
 
-            // Assert
-            result.IsFailed.Should().BeTrue();
-            result.Errors.First().Message.Should().Contain("Не вдалося створити об'єкт мистецтва");
-        }
+        // Assert
+        (await act.Should().ThrowAsync<Exception>())
```
Comment (KobMiles) [inline Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Create/CreateArtHandlerTests.cs:180]: It's not a problem, but why use extra quotation marks? Rewrite it if you think it's necessary.

File: Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Create/CreateArtHandlerTests.cs [hunk 2]
```diff
@@ -12,172 +12,172 @@
...
+        _mockBlobService.Setup(s => s.SaveFileInStorageAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>()))
+            .ThrowsAsync(new InvalidOperationException(expectedExceptionMessage));
 
-            _mockBlobService.Setup(s => s.SaveFileInStorageAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>()))
-                .ReturnsAsync("hashed");
+        // Act
+        Func<Task> act = async () => await _handler.Handle(command, CancellationToken.None);
+
+        // Assert
+        (await act.Should().ThrowAsync<InvalidOperationException>())
```
Comment (KobMiles) [inline Streetcode/Streetcode.XUnitTest/BLL/MediatRTests/Media/Art/Create/CreateArtHandlerTests.cs:150]: It's not a problem, but why use extra quotation marks? Rewrite it if you think it's necessary.

**Review by KobMiles — CHANGES_REQUESTED** [review]
That's good, but there are some minor issues.
The main problem is that there is still a test that does not run, namely: 'UpdateArtHandlerTests'. 
image
Please fix this.

**Review by KobMiles — APPROVED** [review]

**Review by Tolia645 — APPROVED** [review]
✊
